Ios preroll
SuaMusica/flutter_plugins pull request #146
Opened 2024-04-17 14:16 UTC by felipecastrosales

only to track

@coderabbitai: ignore

2024-05-03 19:50 UTC, lstonussi commented on packages/ads/ios/Classes/SwiftSmadsPlugin.swift
> +             SwiftSmadsPlugin.registrarAds!.register(viewFactory, withId: "suamusica/pre_roll_view")
nao seria bom colocar uma verificacao se registrarAds esta nil? é improvavel que esteja mas bom se assegurar

2024-05-03 19:50 UTC, lstonussi commented on packages/ads/ios/Classes/SwiftSmadsPlugin.swift
> +                            SwiftSmadsPlugin.adsViewController!.setup(
verificar adsViewController == nil ou usar ?

2024-05-07 16:40 UTC, atrope requested changes
Veja os comentarios e o que mandei no Discord. o resto ta ok!

2024-05-07 16:40 UTC, atrope commented on packages/ads/ios/Classes/SwiftSmadsPlugin.swift
> +        print("Registering plugin at registrar: \(registrar), datetime: \(Date()), SwiftSmadsPlugin.channel: \(String(describing: SwiftSmadsPlugin.channel))")
remove print

2024-05-07 16:40 UTC, atrope commented on packages/ads/ios/Classes/SwiftSmadsPlugin.swift
> +class FLNativeViewFactory: NSObject, FlutterPlatformViewFactory {
seria melhor outro arquivo nao? mais organizado

2024-05-07 16:40 UTC, atrope commented on packages/ads/ios/Classes/AdsViewController.swift
> +
usar isso do bot?

2024-05-07 16:40 UTC, atrope commented on packages/ads/ios/Classes/AdsViewController.swift
> +
gostei da sugestao˜!

2024-05-07 18:51 UTC, merged