Chaging to V2 Embedding
SuaMusica/flutter_plugins pull request #82
Opened 2021-02-06 19:32 UTC by atrope

2021-02-08 22:42 UTC, nferreira requested changes

2021-02-08 22:42 UTC, nferreira commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaService.kt
> +        Thread(Runnable {
Oi @atrope, por que você trocou o AsyncTask? Você tá gerando um thread toda vez. O AsyncTask reusa threads.

2021-02-08 22:43 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaService.kt
> +        Thread(Runnable {
@nferreira,

Asynctask está deprecated. Como vc faria para substituir? Eu procurei na internet e recomendaram assim

2021-02-12 16:53 UTC, nferreira approved these changes

2021-02-12 16:56 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaService.kt
> +        Thread(Runnable {
@nferreira ??

2021-02-12 17:03 UTC, frisone3d commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaControlBroadcastReceiver.kt
> +            if (intent.hasExtra("favorite")) {
criar constante "favorite"

2021-02-12 17:04 UTC, frisone3d commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaService.kt
> +            onGoing = if (isPlayingExternal == null) {
não pode em kotlin colocar if (isPlayingExternal) {...?

2021-02-12 17:06 UTC, frisone3d commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaSessionConnection.kt
> +            bundle.putBoolean("isFavorite", media.isFavorite)
constante "isFavorite"

2021-02-12 17:06 UTC, frisone3d commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaSessionConnection.kt
> +            bundle.putBoolean("isPlaying", isFavorite)
constante isPlaying

2021-02-12 17:08 UTC, frisone3d commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/PlayerPlugin.kt
> -            Log.i(TAG, "registerWith: START")
precisa ser info mesmo?

2021-02-12 17:19 UTC, atrope reviewed
@frisone3d done

2021-02-12 17:19 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaControlBroadcastReceiver.kt
> +            if (intent.hasExtra("favorite")) {
done

2021-02-12 17:19 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaService.kt
> +            onGoing = if (isPlayingExternal == null) {
nao quando pode ser nulo

2021-02-12 17:19 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaSessionConnection.kt
> +            bundle.putBoolean("isFavorite", media.isFavorite)
done

2021-02-12 17:19 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/MediaSessionConnection.kt
> +            bundle.putBoolean("isPlaying", isFavorite)
done

2021-02-12 17:19 UTC, atrope commented on packages/player/android/src/main/kotlin/br/com/suamusica/player/PlayerPlugin.kt
> -            Log.i(TAG, "registerWith: START")
isso foi o removido.

2021-02-12 17:21 UTC, frisone3d approved these changes

2021-02-12 19:34 UTC, merged