Feature/null safety upgrade ads
SuaMusica/flutter_plugins pull request #85
Opened 2021-03-10 20:59 UTC by 4rthurmonteiro

2021-03-10 21:10 UTC, 4rthurmonteiro commented
no OneApp vão ser gerados dois erros mas é só colocar o "!" que roda. Eles nunca serão nulos até onde vi e testei.

2021-03-11 09:14 UTC, atrope requested changes

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/pre_roll_controller.dart
> +  Future<int?> get screenStatus async =>
evitar devolver int? vamos tratar dentro.

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/smads.dart
> +    final int? result = await _channel.invokeMethod('load', args);
trataqr dentro e devolver int

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/smads.dart
> +          lastAd!.onComplete!();
lastAd?.onComplete?.call()

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/smads.dart
> +          lastAd!.onComplete!();
faz o mesmo os outros

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/pre_roll_event_handler.dart
> +      final type = args["type"] as String?;
final String? type = args["type"]

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/pre_roll.dart
> +    controller!.play();
vamos preferir sempre por ser mais seguros.

controller?.play()

2021-03-11 09:14 UTC, atrope commented on packages/ads/lib/pre_roll.dart
> +    controller!.play();
ou colocar required acima.

2021-03-11 11:11 UTC, atrope requested changes

2021-03-11 11:11 UTC, atrope commented on packages/ads/lib/smads.dart
> +  Stream<AdEvent>? get onEvent {
aqui nunca é null

2021-03-11 13:12 UTC, 4rthurmonteiro commented on packages/ads/lib/pre_roll_controller.dart
> +  Future<int?> get screenStatus async =>
beleza

2021-03-11 13:14 UTC, 4rthurmonteiro commented on packages/ads/lib/pre_roll.dart
> +    controller!.play();
coloquei o controller?

2021-03-11 13:25 UTC, 4rthurmonteiro commented on packages/ads/lib/pre_roll_event_handler.dart
> +      final type = args["type"] as String?;
certo

2021-03-11 13:31 UTC, 4rthurmonteiro commented on packages/ads/lib/smads.dart
> +    final int? result = await _channel.invokeMethod('load', args);
beleza, coloquei ?? 0, ou melhor colocar -1?

2021-03-11 18:22 UTC, 4rthurmonteiro commented on packages/ads/lib/smads.dart
> +  Stream<AdEvent>? get onEvent {
ok

2021-03-11 18:27 UTC, 4rthurmonteiro commented on packages/ads/lib/smads.dart
> +          lastAd!.onComplete!();
beleza

2021-03-12 09:23 UTC, atrope approved these changes
@4rthurmonteiro so mudar ali o ! por ? e ta otimo

2021-03-12 09:23 UTC, atrope commented on packages/ads/lib/smads.dart
> +        lastAd!.onError?.call(error);
evita erro. lastAd?.

2021-03-12 13:02 UTC, 4rthurmonteiro commented on packages/ads/lib/smads.dart
> +        lastAd!.onError?.call(error);
vou mudar

2021-03-12 13:11 UTC, 4rthurmonteiro commented on packages/ads/lib/smads.dart
> +        lastAd!.onError?.call(error);
feito

2021-03-12 13:11 UTC, merged