Feature/null safety upgrade migration
SuaMusica/flutter_plugins pull request #86
Opened 2021-03-10 23:09 UTC by lstonussi

Plugin Migration

2021-03-11 09:06 UTC, atrope requested changes

2021-03-11 09:06 UTC, atrope commented on packages/migration/lib/entities/album.dart
> +        'vip': this.isVerified ?? false ? 1 : 0,
nao faz sentido

2021-03-11 09:06 UTC, atrope commented on packages/migration/lib/entities/album.dart
> +    required this.isVerified,
required e pode ser null?

2021-03-11 09:06 UTC, atrope commented on packages/migration/lib/migration.dart
>      }
_instance ??= Migration._();
    return _instance!;

2021-03-11 09:06 UTC, atrope commented on packages/migration/lib/entities/media.dart
> +  final int? id;
tudo pode ser null?

2021-03-11 16:13 UTC, lstonussi commented on packages/migration/lib/entities/album.dart
> +    required this.isVerified,
ajustado

2021-03-11 16:13 UTC, lstonussi commented on packages/migration/lib/migration.dart
>      }
feito

2021-03-11 16:13 UTC, lstonussi commented on packages/migration/lib/entities/media.dart
> +  final int? id;
ajustado

2021-03-11 18:53 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/Id3.dart
se vc no fromJson já ta tratando isso, precisa ter String? em Artist e em album? faz igual ao q tu faz no path, faz sentido isso?

2021-03-11 18:57 UTC, lstonussi commented on packages/migration/lib/entities/Id3.dart
é que só o path é requerido, os outros são opcionais, se eu não colocar o ? na frente do  artist e album vai reclamar que precisa ser required

2021-03-11 19:08 UTC, 4rthurmonteiro approved these changes
Fiz uns comentários apenas dando umas dicas.

2021-03-11 19:08 UTC, 4rthurmonteiro commented on packages/migration/lib/migration.dart
>        return result;
evita fazer cast

2021-03-11 19:08 UTC, 4rthurmonteiro commented on packages/migration/lib/migration.dart
>                .where((item) => item is Map<dynamic, dynamic>)
aqui tb

2021-03-11 19:08 UTC, 4rthurmonteiro commented on packages/migration/lib/migration.dart
>                (call.arguments as Map<dynamic, dynamic>));
e aqui

2021-03-11 19:08 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/playlist.dart
> +        'isverified': this.isVerified ?? false ? 1 : 0,
tira o ? do isVerified. Ele nunca será null já que no fromJson se for null vc ta jogando false. Então ai só seria this.isVerified ? 1 : 0 pq o sqlite n trabalha com bool.

2021-03-11 19:08 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/playlist.dart
> +        id: json.parseToInt('id') ?? -1,
mesma coisa aqui do parseToInt

2021-03-11 19:08 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/media.dart
> +        isExternal: json['is_external'] ?? false,
isExternal n precisa de ?, ele nunca será nulo.

2021-03-11 19:16 UTC, lstonussi commented on packages/migration/lib/entities/album.dart
> +      id: json.parseToInt('id') ?? -1,
tem razão, vou mudar

2021-03-11 19:19 UTC, lstonussi commented on packages/migration/lib/entities/media.dart
> +        isExternal: json['is_external'] ?? false,
pq nunca será nulo?

2021-03-11 19:19 UTC, lstonussi commented on packages/migration/lib/entities/playlist.dart
> +        id: json.parseToInt('id') ?? -1,
mudarei o parse

2021-03-11 19:20 UTC, lstonussi commented on packages/migration/lib/entities/playlist.dart
> +        'isverified': this.isVerified ?? false ? 1 : 0,
o isVerified pode ser nulo.

2021-03-11 19:22 UTC, lstonussi commented on packages/migration/lib/migration.dart
>        return result;
Não entendi

2021-03-11 22:43 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/media.dart
> +        isExternal: json['is_external'] ?? false,
isExternal: json['is_external'] ?? false,

2021-03-11 22:44 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/playlist.dart
> +        'isverified': this.isVerified ?? false ? 1 : 0,
isVerified: json['is_verified'] ?? false. Se vier null da api ele será false. Então ele nunca será nulo.

2021-03-12 09:22 UTC, atrope approved these changes
Apenas os pontos do @4rthurmonteiro

2021-03-12 11:52 UTC, lstonussi commented on packages/migration/lib/entities/playlist.dart
> +        'isverified': this.isVerified ?? false ? 1 : 0,
feito

2021-03-12 12:06 UTC, lstonussi commented on packages/migration/lib/entities/media.dart
> +        isExternal: json['is_external'] ?? false,
feito

2021-03-12 12:06 UTC, lstonussi commented on packages/migration/lib/migration.dart
>                .where((item) => item is Map<dynamic, dynamic>)
não entendi

2021-03-12 13:14 UTC, 4rthurmonteiro commented on packages/migration/lib/entities/Id3.dart
beleza

2021-03-12 13:20 UTC, 4rthurmonteiro commented on packages/migration/lib/migration.dart
>        return result;
aqui eu vi errado. ta "is" Ali, jurava que era as. Deixa pra lá :)

2021-03-12 13:24 UTC, lstonussi commented on packages/migration/lib/migration.dart
>                .where((item) => item is Map<dynamic, dynamic>)
ajustado

2021-03-12 13:24 UTC, lstonussi commented on packages/migration/lib/migration.dart
>                (call.arguments as Map<dynamic, dynamic>));
ajustado

2021-03-12 13:25 UTC, lstonussi commented on packages/migration/lib/migration.dart
>        return result;
Aquie é is, não as

2021-03-12 13:44 UTC, merged