upgrade player to null safe
SuaMusica/flutter_plugins pull request #87
Opened 2021-03-11 10:41 UTC by atrope

2021-03-11 19:19 UTC, 4rthurmonteiro requested changes

2021-03-11 19:19 UTC, 4rthurmonteiro commented on packages/player/example/lib/sm_player.dart
> +  Duration? position = Duration(seconds: 0);
durantion pode ser nulo?

2021-03-11 19:19 UTC, 4rthurmonteiro commented on packages/player/lib/src/media.dart
>      this.isFavorite,
default de isFavorite pode ser false não? que ai ja retirava o ? dele.

2021-03-11 19:34 UTC, lstonussi commented on packages/player/example/lib/sm_player.dart
>      final cookies = await signer.getCookiesForCustomPolicy(
esses 2 parametros null oq acontece com eles?

2021-03-11 19:54 UTC, lstonussi commented on packages/player/lib/src/event.dart
> +    this.media,
media não é required?

2021-03-12 08:58 UTC, atrope commented on packages/player/lib/src/media.dart
>      this.isFavorite,
por enquanto nao, enquanto nao fizer a issue da semana pode ser null, após a issue vamos mudar aqui.

2021-03-12 09:00 UTC, atrope commented on packages/player/example/lib/sm_player.dart
> +  Duration? position = Duration(seconds: 0);
é o exemplo  só, mas voce esta certo. done

2021-03-12 09:01 UTC, atrope commented on packages/player/example/lib/sm_player.dart
>      final cookies = await signer.getCookiesForCustomPolicy(
são parametros extras da AWS que nao usamos.

2021-03-12 09:20 UTC, atrope commented on packages/player/lib/src/event.dart
> +    this.media,
fixed

2021-03-12 13:01 UTC, lstonussi approved these changes

2021-03-12 13:13 UTC, 4rthurmonteiro approved these changes

2021-03-12 13:37 UTC, merged